### ISSUE TITLE
CodeBird Transient Errors

### ISSUE THREAD

**Issue by edent** [edent/Dabr#45]
Sometimes CodeBird throws a wobbly.  Either returns an empty set (fine after refresh) or a malformed object (fine on refresh).

Transient and hard to pin down.  Maybe validate the object before processing?

**Comment by edent** [comment]
```

Fatal error: Uncaught exception 'Exception' with message 'Request error for API call: Connection timed out after 3002 milliseconds' in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php:1525 Stack trace: #0 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(1476): Codebird\Codebird->_callApiCurl('GET', 'statuses/home_t...', Array, false, false) #1 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(508): Codebird\Codebird->_callApi('GET', 'statuses/home_t...', Array, false, false) #2 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(1531): Codebird\Codebird->__call('statuses_homeTi...', Array) #3 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(1531): Codebird\Codebird->statuses_homeTimeline('&count=20&scree...') #4 [internal function]: twitter_home_page(Array) #5 /var/sites/s/shkspr.mobi/public_html/dabr2/common/menu.php(30): call_user_func('twitter_home_pa...', Array) #6 /var/sites/s/shkspr.mobi/public_html/dabr2/index.php(52): menu_execute_active_handler() #7 in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php on line 1525
```

**Comment by edent** [comment]
```

Fatal error: Uncaught exception 'Exception' with message 'Request error for API call: Failed to connect to api.twitter.com port 443: Connection refused' in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php:1525
Stack trace: #0 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(1476): Codebird\Codebird->_callApiCurl('POST', 'friendships/cre...', Array, false, false) 
#1 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(508): Codebird\Codebird->_callApi('POST', 'friendships/cre...', Array, false, false) 
#2 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(765): Codebird\Codebird->__call('friendships_cre...', Array) 
#3 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(765): Codebird\Codebird->friendships_create(Array) 
#4 [internal function]: twitter_follow_page(Array) 
#5 /var/sites/s/shkspr.mobi/public_html/dabr2/common/menu.php(30): call_user_func('twitter_follow_...', Array) 
#6 /var/sites/s/shkspr.mobi/public_html/dabr2/index.php(52): menu_execute_active_handler( in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php on line 1525
```

**Comment by edent** [comment]
```
Fatal error: Uncaught exception 'Exception' with message 'Request error for API call: Connection timed out after 3002 milliseconds' in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php:1525 Stack trace: #0 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(1476): Codebird\Codebird->_callApiCurl('GET', 'statuses/mentio...', Array, false, false) #1 /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php(508): Codebird\Codebird->_callApi('GET', 'statuses/mentio...', Array, false, false) #2 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(1198): Codebird\Codebird->__call('statuses_mentio...', Array) #3 /var/sites/s/shkspr.mobi/public_html/dabr2/common/twitter.php(1198): Codebird\Codebird->statuses_mentionsTimeline('count=20') #4 [internal function]: twitter_replies_page(Array) #5 /var/sites/s/shkspr.mobi/public_html/dabr2/common/menu.php(30): call_user_func('twitter_replies...', Array) #6 /var/sites/s/shkspr.mobi/public_html/dabr2/index.php(63): menu_execute_active_handler() #7 {ma in /var/sites/s/shkspr.mobi/public_html/dabr2/common/codebird.php on line 1525
```
